name 'formatron_apache'
version '0.1.3'
description 'Formatron Apache cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/apache-cookbook'
issues_url 'https://github.com/formatron/apache-cookbook/issues'
supports 'ubuntu'
depends 'apache2'
