name 'formatron_apache'
version '0.1.1'
description 'Formatron Apache cookbook'
source_url 'https://github.com/formatron/apache-cookbook'
issues_url 'https://github.com/formatron/apache-cookbook/issues'
supports 'ubuntu'
depends 'apache2'
